language: julia
os:
  - linux
julia:
  - 1.0

notifications:
  email: false

script:
  - julia -e 'using Pkg; Pkg.test("LambertWExp"; coverage=true)'

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage")'
  - julia -e 'cd(Pkg.dir("LambertWExp")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'